### PR TITLE
Fix Druid Crystallized Firestone List

### PR DESCRIPTION
**Pull request by Arcanemagus**
Druids are unable to use wands, so they will _never_ be able to obtain the two items currently listed for them:
* [Trail of Embers](https://www.wowhead.com/item=71575) (`71575`)
* [Scorchvine Wand](https://www.wowhead.com/item=71579) (`71579`)

_Note: If you would prefer the whitespace cleanup to be removed from this PR just let me know!_

### CODE REVIEW

**Comment by Arcanemagus** [comment]
Bump 😉.

**Comment by Kruithne** [comment]
Apologies that I never got around to checking this. Maintaining add-ons is very much on the back-burner at the moment.

Looking at the PR it seems like it introduces a large quantity of line-breaks for no reason? If possible, could you fix that so that it is only changing the data and not introducing line-breaks everywhere. Thanks!

**Comment by Arcanemagus** [comment]
Rebased without the whitespace changes.

**Comment by Kruithne** [comment]
Thank you kindly.

**Pull request merged**
